module.exports = {
    'likes': '{ likes, number } me gusta',
    'logout': 'Salir',
    'english': 'Inglés',
    'spanish': 'Español',
    'signup.subheading': 'Registrate para ver fotos de tu red Uppic Platzi',
    'signup.facebook': 'Iniciar sesión con Facebook',
    'signup.google': 'Iniciar sesión con Google',
    'signup.text': 'Iniciar sesión',
    'email': 'Correo electrónico',
    'username': 'Nombre de usuario',
    'fullname': 'Nombre completo',
    'password': 'Contraseña',
    'signup.call-to-action': 'Regístrate',
    'signup.have-account': '¿Tienes una cuenta?',
    'signin': 'Entrar',
    'signin.not-have-account': '¿No tienes una cuenta?',
    'language': 'Idioma',
    'upload-picture': 'Subir foto',
    'upload': 'Subir'
  }